services:
  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
    ports:
      - "127.0.0.1:8082:80"
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-qcv}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-qcv}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "0.0.0.0:7082:8080"
