<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260908093756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78672EEAB6E62EFA ON attribute_option (attribute_id)');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_78672EEAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_value ADD version INT NOT NULL');
        $this->addSql('ALTER TABLE attribute_value ADD value_option_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB82E25618D9 FOREIGN KEY (value_option_id) REFERENCES attribute_option (id)');
        $this->addSql('CREATE INDEX IDX_FE4FBB82E25618D9 ON attribute_value (value_option_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_78672EEAB6E62EFA');
        $this->addSql('DROP TABLE attribute_option');
        $this->addSql('ALTER TABLE attribute_value DROP CONSTRAINT FK_FE4FBB82E25618D9');
        $this->addSql('DROP INDEX IDX_FE4FBB82E25618D9');
        $this->addSql('ALTER TABLE attribute_value DROP version');
        $this->addSql('ALTER TABLE attribute_value DROP value_option_id');
    }
}
