<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260920153748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT fk_af5bee86dd842e46');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT fk_af5bee86b6e62efa');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT position_attribute_pkey');
        $this->addSql('ALTER TABLE position_attribute ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86DD842E46');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86B6E62EFA');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT position_attribute_pkey');
        $this->addSql('ALTER TABLE position_attribute DROP id');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT fk_af5bee86dd842e46 FOREIGN KEY (position_id) REFERENCES "position" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT fk_af5bee86b6e62efa FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE position_attribute ADD PRIMARY KEY (position_id, attribute_id)');
    }
}
