<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260921133109 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operation VARCHAR(255) NOT NULL, match_type VARCHAR(255) NOT NULL, attribute_dimension VARCHAR(255) NOT NULL, filter_value_type VARCHAR(255) DEFAULT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B001CACADD842E46 ON access_rule (position_id)');
        $this->addSql('CREATE INDEX IDX_B001CACAB6E62EFA ON access_rule (attribute_id)');
        $this->addSql('ALTER TABLE access_rule ADD CONSTRAINT FK_B001CACADD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_rule ADD CONSTRAINT FK_B001CACAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CV ON cv (position_id, candidate_id)');
        $this->addSql('ALTER TABLE position_attribute ADD is_required BOOLEAN DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_POSITION_ATTRIBUTE ON position_attribute (position_id, attribute_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE access_rule DROP CONSTRAINT FK_B001CACADD842E46');
        $this->addSql('ALTER TABLE access_rule DROP CONSTRAINT FK_B001CACAB6E62EFA');
        $this->addSql('DROP TABLE access_rule');
        $this->addSql('DROP INDEX UNIQ_CV');
        $this->addSql('DROP INDEX UNIQ_POSITION_ATTRIBUTE');
        $this->addSql('ALTER TABLE position_attribute DROP is_required');
    }
}
