<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260901130608 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, data_type VARCHAR(255) NOT NULL, is_builtin BOOLEAN NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB12469DE2 ON attribute (category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ATTRIBUTE_NAME ON attribute (name)');
        $this->addSql('CREATE TABLE attribute_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ATTRIBUTE_CATEGORY_NAME ON attribute_category (name)');
        $this->addSql('CREATE TABLE attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value_string VARCHAR(255) DEFAULT NULL, value_text TEXT DEFAULT NULL, value_numeric NUMERIC(10, 2) DEFAULT NULL, value_date DATE DEFAULT NULL, value_date_end DATE DEFAULT NULL, value_boolean BOOLEAN DEFAULT NULL, candidate_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE4FBB8291BD8781 ON attribute_value (candidate_id)');
        $this->addSql('CREATE INDEX IDX_FE4FBB82B6E62EFA ON attribute_value (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ATTRIBUTE_VALUE ON attribute_value (candidate_id, attribute_id)');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB12469DE2 FOREIGN KEY (category_id) REFERENCES attribute_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB8291BD8781 FOREIGN KEY (candidate_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB82B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_PROVIDER ON oauth_account (provider, provider_user_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute DROP CONSTRAINT FK_FA7AEFFB12469DE2');
        $this->addSql('ALTER TABLE attribute_value DROP CONSTRAINT FK_FE4FBB8291BD8781');
        $this->addSql('ALTER TABLE attribute_value DROP CONSTRAINT FK_FE4FBB82B6E62EFA');
        $this->addSql('DROP TABLE attribute');
        $this->addSql('DROP TABLE attribute_category');
        $this->addSql('DROP TABLE attribute_value');
        $this->addSql('DROP INDEX UNIQ_USER_PROVIDER');
    }
}
