<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260912181413 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, max_projects INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE position_attribute (position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (position_id, attribute_id))');
        $this->addSql('CREATE INDEX IDX_AF5BEE86DD842E46 ON position_attribute (position_id)');
        $this->addSql('CREATE INDEX IDX_AF5BEE86B6E62EFA ON position_attribute (attribute_id)');
        $this->addSql('CREATE TABLE position_tag (position_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (position_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_F73FBF9BDD842E46 ON position_tag (position_id)');
        $this->addSql('CREATE INDEX IDX_F73FBF9BBAD26311 ON position_tag (tag_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, description TEXT DEFAULT NULL, candidate_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE91BD8781 ON project (candidate_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TAG_NAME ON tag (name)');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_tag ADD CONSTRAINT FK_F73FBF9BDD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_tag ADD CONSTRAINT FK_F73FBF9BBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE91BD8781 FOREIGN KEY (candidate_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86DD842E46');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86B6E62EFA');
        $this->addSql('ALTER TABLE position_tag DROP CONSTRAINT FK_F73FBF9BDD842E46');
        $this->addSql('ALTER TABLE position_tag DROP CONSTRAINT FK_F73FBF9BBAD26311');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE91BD8781');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE position_attribute');
        $this->addSql('DROP TABLE position_tag');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE tag');
    }
}
