<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922063549 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "like" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recruiter_id INT NOT NULL, cv_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC6340B3156BE243 ON "like" (recruiter_id)');
        $this->addSql('CREATE INDEX IDX_AC6340B3CFE419E2 ON "like" (cv_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LIKE ON "like" (recruiter_id, cv_id)');
        $this->addSql('ALTER TABLE "like" ADD CONSTRAINT FK_AC6340B3156BE243 FOREIGN KEY (recruiter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "like" ADD CONSTRAINT FK_AC6340B3CFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_rule DROP CONSTRAINT fk_b001cacadd842e46');
        $this->addSql('ALTER TABLE access_rule ADD CONSTRAINT FK_B001CACADD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD is_public BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT fk_af5bee86dd842e46');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "like" DROP CONSTRAINT FK_AC6340B3156BE243');
        $this->addSql('ALTER TABLE "like" DROP CONSTRAINT FK_AC6340B3CFE419E2');
        $this->addSql('DROP TABLE "like"');
        $this->addSql('ALTER TABLE access_rule DROP CONSTRAINT FK_B001CACADD842E46');
        $this->addSql('ALTER TABLE access_rule ADD CONSTRAINT fk_b001cacadd842e46 FOREIGN KEY (position_id) REFERENCES "position" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cv DROP is_public');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86DD842E46');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT fk_af5bee86dd842e46 FOREIGN KEY (position_id) REFERENCES "position" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
